spring:
  output.ansi.enabled: always
logging:
  pattern.console: "%d{yyyy-MM-dd' 'HH:mm:ss}|%clr(%-5level)|%-50logger{36}: %clr(%msg%n)"
  level:
    root: INFO
    org:
      apache.catalina: OFF
      hibernate.SQL: INFO
      springframework:
        orm.jpa.JpaTransactionManager: INFO
        transaction.interceptor: INFO