spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      jdbc: time_zone
    properties:
      hibernate:
        format_sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/postgres
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: always
logging:
  pattern:
    console: "%d{yyyy-MM-dd' 'HH:mm:ss}|%clr(%-5level)|%-50logger{36}: %clr(%msg%n)"
  level:
    org:
      apache.catalina: OFF
      hibernate.SQL: INFO  # Для логирования SQL-запросов
      springframework:
        orm.jpa.JpaTransactionManager: INFO
        transaction.interceptor: INFO
