server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      properties:
        hibernate.format_sql: true
        hibernate.jdbc.time_zone: UTC # Установите нужный временной пояс

  sql:
    init:
      enabled: false

jvm-args:
  -Xshare: off
