server.port: 9090
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true
      jdbc: time_zone
    properties.hibernate.format_sql: true
  jvm-args:
    -Xshare:off
  sql.init:
    enabled: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
